### PR TITLE
Fixed px-tooltip text overflow the container on IE11

### PR DESCRIPTION
**Pull request by dchinnam**
# Pull Request

Hi,

Thanks for helping us improve the Predix UI platform by submitting a Pull Request.

To help us merge your Pull Request as fast as possible, please fill out the following sections:

* ## A description of the changes proposed in the pull request:  Fixed px-tooltip text overflow the container on IE11. overflow-wrap is not supported on IE 11, replaced this with word-wrap which works on both IE11 and chrome

* ## A reference to a related issue (if applicable):

* ## @mentions of the person or team responsible for reviewing proposed changes: Avid Analysis

* ## working tests:

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi,

Can you resubmit this following the template provided when you create a new PR. We can't accept a PR that we don't know why you submitted it.

Thanks.

**Comment by mdwragg** [comment]
Also the tests are failing, we can't merge a PR in this state. Thanks.

**Comment by benoitjchevalier** [comment]
After discussion and code review this looks ok. Thanks for the PR!

Next time try to fill out the template a bit more, it helps for other people on our team to review a PR or for anyone else referring to it in the future (this is all public)

For future references:

This PR changes `overflow-wrap` to `word-wrap` since IE doesn't support `overflow-wrap`: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by benoitjchevalier** [comment]
Available in v1.2.1

**Pull request merged**
